name: PromptHub

options:
  minimumXcodeGenVersion: 2.30.0
  developmentLanguage: zh-Hans
  deploymentTarget:
    macOS: "13.0"

settings:
  base:
    SWIFT_VERSION: 5.9

targets:
  PromptHub:
    type: application
    platform: macOS
    sources:
      - path: app
      - path: Resources
    info:
      path: Config/Info.plist
      properties:
        CFBundleDisplayName: PromptHub
        CFBundleName: PromptHub
        CFBundleShortVersionString: 0.1.0
        CFBundleVersion: 1
        LSApplicationCategoryType: public.app-category.developer-tools
        NSHighResolutionCapable: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.prompthub.app
        CODE_SIGN_STYLE: Automatic
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 0.1.0

schemes:
  PromptHub:
    build:
      targets:
        PromptHub: all
    run:
      config: Debug
